env:
  browser: true
  es6: true
extends: [ "standard", "prettier", "prettier/standard" ]
plugins: [ "import", "prettier", "standard" ]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
env:
  browser: true